# config/services.yaml
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    cours_images_directory: '%kernel.project_dir%/public/uploads/cours'
    upload_directory: '%kernel.project_dir%/public/uploads/photos'
    modules_pdfs_directory: '%kernel.project_dir%/public/uploads/modules_pdfs'
    discord_bot_token: '%env(DISCORD_BOT_TOKEN)%'
    discord_guild_id: '%env(DISCORD_GUILD_ID)%'

services:
     # Register the form type as a service
    App\Form\InstructeurRegistrationFormType:
        arguments:
            $uploadDirectory: '%upload_directory%'
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.



    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # DiscordService
    App\Service\DiscordService:
        arguments:
            $botToken: '%discord_bot_token%'
            $guildId: '%discord_guild_id%'

    # ProfanityFilterService
    App\Service\ProfanityFilterService:
        autowire: true
        autoconfigure: true


    # Event Listeners
    App\EventListener\LoginListener:
        class: App\EventListener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }

    App\EventListener\AdminAccessListener:
        class: App\EventListener\AdminAccessListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }