# config/services.yaml
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    cours_images_directory: '%kernel.project_dir%/public/uploads/cours'
    upload_directory: '%kernel.project_dir%/public/uploads/photos'
    discord_bot_token: '%env(DISCORD_BOT_TOKEN)%'
    discord_guild_id: '%env(DISCORD_GUILD_ID)%'

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true
        autoconfigure: true

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # DiscordService
    App\Service\DiscordService:
        arguments:
            $botToken: '%discord_bot_token%'
            $guildId: '%discord_guild_id%'

    # ProfanityFilterService
    App\Service\ProfanityFilterService:
        autowire: true
        autoconfigure: true

    # Remove the arguments for InstructeurRegistrationFormType since it doesn't need them
    App\Form\InstructeurRegistrationFormType:
        autowire: true
        autoconfigure: true

    # Event Listeners
    App\EventListener\LoginListener:
        class: App\EventListener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }

    App\EventListener\AdminAccessListener:
        class: App\EventListener\AdminAccessListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }